
name: TreinaZap - Deploy PRD - to ECS

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: dopplerhq/cli-action@v1
      - name: SET ENVS AGENT GITHUB ACTIONS
        run: doppler secrets download --no-file --format=docker >> $GITHUB_ENV;
        env:
            DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRD }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.21.0
      - name: SET ENV FIREBASE
        run: envsubst <src/firebase-deploy.js> src/firebase.js
      - name: CHECK FILE
        run: cat src/firebase.js
      - name: INSTALL AND BUILD
        run: npm install && npm run build
        env:
            CI: "false"
      - name: DOWNLOAD SONAR-SCANNER
        run: wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip && unzip sonar-scanner-cli-4.6.0.2311-linux.zip
      - name: ANALYSYS CODE
        run: ./sonar-scanner-4.6.0.2311-linux/bin/sonar-scanner -Dsonar.projectKey=treinazap -Dsonar.sources=. -Dsonar.host.url=http://sonar.pitu.ga/ -Dsonar.login=5a0cbf20b7b75624b309f398f722ed4c409800f2

      - name: CLEAR CACHE
        run: AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY} aws cloudfront create-invalidation --distribution-id ${AWS_CF_DISTRIBUTION_ID} --path '/*'
        
